version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 127.0.0.1:3000:3000
